In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt  

df = pd.read_csv('phishing_dataset.csv')
df

       -1  1  1.1  1.2  -1.1  -1.2  ...  -1.13  -1.14  1.11  1.12  -1.15  -1.16
0       1  1    1    1     1    -1  ...      0     -1     1     1      1     -1
1       1  0    1    1     1    -1  ...      1     -1     1     0     -1     -1
2       1  0    1    1     1    -1  ...      1     -1     1    -1      1     -1
3       1  0   -1    1     1    -1  ...      0     -1     1     1      1      1
4      -1  0   -1    1    -1    -1  ...      1     -1     1    -1     -1      1
...    .. ..  ...  ...   ...   ...  ...    ...    ...   ...   ...    ...    ...
11049   1 -1    1   -1     1     1  ...     -1     -1     1     1      1      1
11050  -1  1    1   -1    -1    -1  ...      1      1     1    -1      1     -1
11051   1 -1    1    1     1    -1  ...      1     -1     1     0      1     -1
11052  -1 -1    1    1     1    -1  ...      1     -1     1     1      1     -1
11053  -1 -1    1    1     1    -1  ...     -1     -1    -1     1     -1     -1

[11054 rows x 31 columns]

In [0]:
y = df.iloc[:, -1].values
X = df.iloc[:, :-1].values

In [0]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
         X, y, test_size=0.2, random_state=0)

SVM

In [0]:
from sklearn.svm import SVC

svm = SVC(kernel='poly', C=1.0, random_state=0)
svm.fit(X_train, y_train)

y_pred = svm.predict(X_test)

In [15]:
from sklearn.metrics import accuracy_score

print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.4f' % accuracy_score(y_test, y_pred))

Misclassified samples: 94
Accuracy: 0.9575

Logistic Regression

In [0]:

from sklearn.linear_model import LogisticRegression
log_classifier = LogisticRegression()

In [17]:
log_classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
predictions = log_classifier.predict(X_test)

In [21]:
accuracy = accuracy_score(y_test, predictions)
print ("Logistic Regression accuracy is: " + str(accuracy))

Logistic Regression accuracy is: 0.926729986431479